package git

import "github.com/kbukum/gokit/git/internal/model"

type OpenOptions = model.OpenOptions
type Option = model.Option
type DiffOptions = model.DiffOptions
type DiffOption = model.DiffOption
type LogOptions = model.LogOptions
type BlameOptions = model.BlameOptions
type BlameOption = model.BlameOption
type CommitOptions = model.CommitOptions
type CommitOption = model.CommitOption
type FetchOptions = model.FetchOptions
type FetchOption = model.FetchOption
type PushOptions = model.PushOptions
type PushOption = model.PushOption
type DescribeOptions = model.DescribeOptions
type DescribeOption = model.DescribeOption
type GrepOptions = model.GrepOptions
type GrepOption = model.GrepOption
type MergeOptions = model.MergeOptions
type MergeOption = model.MergeOption
type RebaseOptions = model.RebaseOptions
type RebaseOption = model.RebaseOption
type CherryPickOptions = model.CherryPickOptions
type CherryPickOption = model.CherryPickOption
type CheckoutOptions = model.CheckoutOptions
type CheckoutOption = model.CheckoutOption
type CleanOptions = model.CleanOptions
type CleanOption = model.CleanOption

var (
	WithPreferCLI                 = model.WithPreferCLI
	WithCLIPath                   = model.WithCLIPath
	WithTransport                 = model.WithTransport
	WithSigning                   = model.WithSigning
	WithExtraArgs                 = model.WithExtraArgs
	WithDiffContext               = model.WithDiffContext
	WithDiffNameOnly              = model.WithDiffNameOnly
	WithDiffExtraArgs             = model.WithDiffExtraArgs
	WithLogExtraArgs              = model.WithLogExtraArgs
	WithLineRange                 = model.WithLineRange
	WithIgnoreWhitespace          = model.WithIgnoreWhitespace
	WithBlameExtraArgs            = model.WithBlameExtraArgs
	WithCommitAuthor              = model.WithCommitAuthor
	WithCommitCommitter           = model.WithCommitCommitter
	WithCommitSign                = model.WithCommitSign
	WithCommitAmend               = model.WithCommitAmend
	WithCommitExtraArgs           = model.WithCommitExtraArgs
	WithFetchPrune                = model.WithFetchPrune
	WithFetchDepth                = model.WithFetchDepth
	WithFetchRefspecs             = model.WithFetchRefspecs
	WithFetchExtraArgs            = model.WithFetchExtraArgs
	WithPushForce                 = model.WithPushForce
	WithPushRefspecs              = model.WithPushRefspecs
	WithPushExtraArgs             = model.WithPushExtraArgs
	WithDescribeMatch             = model.WithDescribeMatch
	WithDescribeAnnotatedTagsOnly = model.WithDescribeAnnotatedTagsOnly
	WithDescribeLong              = model.WithDescribeLong
	WithDescribeAbbreviated       = model.WithDescribeAbbreviated
	WithDescribeAlways            = model.WithDescribeAlways
	WithDescribeExtraArgs         = model.WithDescribeExtraArgs
	WithGrepPathspecs             = model.WithGrepPathspecs
	WithGrepIgnoreCase            = model.WithGrepIgnoreCase
	WithGrepLineNumbers           = model.WithGrepLineNumbers
	WithGrepExtraArgs             = model.WithGrepExtraArgs
	WithMergeCommit               = model.WithMergeCommit
	WithMergeFFOnly               = model.WithMergeFFOnly
	WithMergeNoFastForward        = model.WithMergeNoFastForward
	WithMergeSquash               = model.WithMergeSquash
	WithMergeMessage              = model.WithMergeMessage
	WithMergeExtraArgs            = model.WithMergeExtraArgs
	WithRebaseInteractive         = model.WithRebaseInteractive
	WithRebaseAutosquash          = model.WithRebaseAutosquash
	WithRebaseExtraArgs           = model.WithRebaseExtraArgs
	WithCherryPickMainline        = model.WithCherryPickMainline
	WithCherryPickNoCommit        = model.WithCherryPickNoCommit
	WithCherryPickExtraArgs       = model.WithCherryPickExtraArgs
	WithCheckoutCreateBranch      = model.WithCheckoutCreateBranch
	WithCheckoutForce             = model.WithCheckoutForce
	WithCheckoutDetach            = model.WithCheckoutDetach
	WithCheckoutExtraArgs         = model.WithCheckoutExtraArgs
	WithCleanDirectories          = model.WithCleanDirectories
	WithCleanIgnored              = model.WithCleanIgnored
	WithCleanForce                = model.WithCleanForce
	WithCleanExtraArgs            = model.WithCleanExtraArgs
)
