version: "2"

linters:
  default: standard
  enable:
    - misspell
    - unconvert
    - unparam
    - nakedret
    - prealloc
    - gocritic
    - gosec
    - bodyclose
    - noctx
  exclusions:
    rules:
      - path: "_test\\.go"
        linters:
          - errcheck
          - gosec
  settings:
    govet:
      disable:
        - fieldalignment
    gocritic:
      enabled-tags:
        - diagnostic
        - style
        - performance
      disabled-checks:
        - hugeParam
        - paramTypeCombine  # Prefer explicit types for each parameter for clarity
    nakedret:
      max-func-lines: 30
    misspell:
      locale: US
    gosec:
      excludes:
        - G115
        - G404
        - G306
        - G402  # TLS InsecureSkipVerify - intentional for test/dev configs
        - G304  # File paths from variables - required for storage abstraction
        - G117  # Exported struct fields matching secret patterns - config structs need these fields
        - G704  # SSRF via taint analysis - HTTP clients use configured base URLs

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/kbukum/gokit