version: "2"

linters:
  default: standard
  enable:
    - misspell
    - unconvert
    - unparam
    - nakedret
    - prealloc
    - gocritic
    - gosec
    - bodyclose
    - noctx
  exclusions:
    rules:
      - path: "_test\\.go"
        linters:
          - errcheck
          - gosec
  settings:
    govet:
      disable:
        - fieldalignment
    gocritic:
      enabled-tags:
        - diagnostic
        - style
        - performance
      disabled-checks:
        - hugeParam
    nakedret:
      max-func-lines: 30
    misspell:
      locale: US
    gosec:
      excludes:
        - G115
        - G404
        - G306

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/kbukum/gokit