name: Bug Report
description: Report a bug or unexpected behavior
title: "[Bug]: "
labels: ["bug", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the form below.

  - type: dropdown
    id: module
    attributes:
      label: Module
      description: Which gokit module is affected?
      options:
        - Core (errors, config, logger, util, etc.)
        - auth
        - authz
        - bootstrap
        - component
        - config
        - connect
        - dag
        - database
        - di
        - discovery
        - encryption
        - grpc
        - httpclient
        - kafka
        - logger
        - observability
        - pipeline
        - process
        - provider
        - redis
        - resilience
        - security
        - server
        - sse
        - storage
        - validation
        - version
        - workload
        - Other/Unknown
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: Clear description of what went wrong
      placeholder: "When I call X with Y, I expected Z but got W instead..."
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to Reproduce
      description: Minimal code or steps to reproduce the issue
      placeholder: |
        1. Import `github.com/kbukum/gokit/server`
        2. Create a server with `server.New(...)`
        3. Call `srv.Start(ctx)` and observe...
      render: go
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What should happen?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happens? (Include error messages, stack traces, logs)
      render: shell

  - type: input
    id: version
    attributes:
      label: Version
      description: "Which version of gokit? (e.g., v0.1.2, server/v0.1.1)"
      placeholder: "v0.1.2"
    validations:
      required: true

  - type: input
    id: go-version
    attributes:
      label: Go Version
      description: "Output of `go version`"
      placeholder: "go1.25.1 darwin/arm64"
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other information that might be relevant
