#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(CDPATH= cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(CDPATH= cd -- "${SCRIPT_DIR}/.." && pwd)"
export ROOT_DIR

if [[ -n "${PYTHON:-}" ]]; then
  PYTHON_BIN="$PYTHON"
elif command -v python3.14 >/dev/null 2>&1; then
  PYTHON_BIN="python3.14"
elif command -v python3.13 >/dev/null 2>&1; then
  PYTHON_BIN="python3.13"
elif command -v python3.12 >/dev/null 2>&1; then
  PYTHON_BIN="python3.12"
elif command -v python3.11 >/dev/null 2>&1; then
  PYTHON_BIN="python3.11"
else
  PYTHON_BIN="python3"
fi

if ! command -v "$PYTHON_BIN" >/dev/null 2>&1; then
  echo "Python 3.11+ is required" >&2
  exit 1
fi

"$PYTHON_BIN" <<'PY'
from __future__ import annotations

import os
import sys
import tomllib
from pathlib import Path

if sys.version_info < (3, 11):
    raise SystemExit("Python 3.11+ is required")

DOMAIN_EMOJI = {
    "core": "🧱",
    "patterns": "🔧",
    "crosscutting": "🔄",
    "composition": "🏗️",
    "transport": "🌐",
    "auth": "🔑",
    "data": "💾",
    "ai": "🧠",
    "media": "🎬",
    "infra": "⚙️",
}
DOMAIN_ORDER = [
    "core",
    "patterns",
    "crosscutting",
    "composition",
    "transport",
    "auth",
    "data",
    "ai",
    "media",
    "infra",
]
DOMAIN_TITLES = {
    "core": "Core",
    "patterns": "Patterns",
    "crosscutting": "Cross-cutting",
    "composition": "Composition",
    "transport": "Transport",
    "auth": "Auth",
    "data": "Data",
    "ai": "AI",
    "media": "Media",
    "infra": "Infra",
}

root_dir = Path(os.environ["ROOT_DIR"])
domains_path = root_dir / "domains.toml"
docs_dir = root_dir / "docs"
output_path = docs_dir / "MODULE-INDEX.md"

with domains_path.open("rb") as file:
    data = tomllib.load(file)

domains = data.get("domains", {})
docs_dir.mkdir(parents=True, exist_ok=True)

lines = [
    "# Module Index by Domain",
    "",
    "<!-- Auto-generated by scripts/generate-module-index.sh — do not edit manually -->",
    "",
]

ordered_domains = [domain for domain in DOMAIN_ORDER if domain in domains]
ordered_domains.extend(domain for domain in domains if domain not in DOMAIN_ORDER)

for domain in ordered_domains:
    modules = domains[domain].get("modules", [])
    emoji = DOMAIN_EMOJI.get(domain, "📦")
    title = DOMAIN_TITLES.get(domain, domain.replace("-", " ").title())

    lines.append(f"## {emoji} {title}  (`make check-{domain}`)")
    lines.append(" · ".join(modules))
    lines.append("")

output_path.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")
print(f"Generated {output_path}")
PY
